// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUeU0wqZG4klY7aWZUhVokkvXQklVgU4c',
    appId: '1:513127514444:web:000de3b57647a859f18fe9',
    messagingSenderId: '513127514444',
    projectId: 'hitthedealer-7c1c6',
    authDomain: 'hitthedealer-7c1c6.firebaseapp.com',
    storageBucket: 'hitthedealer-7c1c6.firebasestorage.app',
    measurementId: 'G-SK4M5WFRZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1TSlyNqaHes1bDZSAiE5cLsSgV_DS5s',
    appId: '1:513127514444:android:9aac085244c2e220f18fe9',
    messagingSenderId: '513127514444',
    projectId: 'hitthedealer-7c1c6',
    storageBucket: 'hitthedealer-7c1c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6bkUkcO4vljVUX56skSJvZA-lGPFqvM',
    appId: '1:513127514444:ios:15a57d873ccacbe9f18fe9',
    messagingSenderId: '513127514444',
    projectId: 'hitthedealer-7c1c6',
    storageBucket: 'hitthedealer-7c1c6.firebasestorage.app',
    iosBundleId: 'com.example.hitTheDealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE6bkUkcO4vljVUX56skSJvZA-lGPFqvM',
    appId: '1:513127514444:ios:15a57d873ccacbe9f18fe9',
    messagingSenderId: '513127514444',
    projectId: 'hitthedealer-7c1c6',
    storageBucket: 'hitthedealer-7c1c6.firebasestorage.app',
    iosBundleId: 'com.example.hitTheDealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUeU0wqZG4klY7aWZUhVokkvXQklVgU4c',
    appId: '1:513127514444:web:212a65c6d3141374f18fe9',
    messagingSenderId: '513127514444',
    projectId: 'hitthedealer-7c1c6',
    authDomain: 'hitthedealer-7c1c6.firebaseapp.com',
    storageBucket: 'hitthedealer-7c1c6.firebasestorage.app',
    measurementId: 'G-ZVDGKW3674',
  );
}
